In [1]:
import numpy as np 
# Okay, I lied. But I promise, this will be the only library we will use.

## Define a sigmoid activation function
An activation function maps the input values in between 0 to 1 or -1 to 1, etc. (depending upon the function used). Here, we are using a sigmoid function that looks like an 'S' curve stretching from - infinity to + infinity and the values ranging from 0 to 1.

s(x) = 1/(1+e^(-x))
![Sigmoid](sigmoid.gif)

In [2]:
# sigmoid function
def nonlin(x,deriv=False):
    if(deriv==True):
        return x*(1-x)
    return 1/(1+np.exp(-x))

## What does that mean?
It means, if we pass any number to the above "nonlin" function (let's say 5 and -5 as in the above figure), the output should come accordingly.

In [3]:
nonlin(5) # Check the figure, the value (red curve) is closer to 1 and so is our output.

0.9933071490757153

In [4]:
nonlin(5) # Check the figure, the value (red curve) is closer to 0 and so is our output.

0.9933071490757153

## And now, we define our input and the output data. 

In [5]:
# Declare a variable X with sample input dataset. Woah! Look at this huge dataset! :p
X = np.array([  [0,0,1],
                [0,1,1],
                [1,0,1],
                [1,1,1] ])

# And y as output dataset. Notice we're doing a transpose operation.
y = np.array([[0,0,1,1]]).T

## What do they look like?

In [6]:
X # X is a 4 by 3 dimensional array

array([[0, 0, 1],
       [0, 1, 1],
       [1, 0, 1],
       [1, 1, 1]])

In [7]:
y # And y is a 4 by 1 dimensional array

array([[0],
       [0],
       [1],
       [1]])

In [11]:
# random initialization of weights as 3 by 1 matrix
np.random.seed(1)
syn0 = 2*np.random.random((3,1)) - 1
# Seeding will always yeild the same result. [[-0.16595599],[ 0.44064899], [-0.99977125]]

for each_iteration in range(10000):

    # forward propagation
    l0 = X
    l1 = nonlin(np.dot(l0,syn0))

    # how much did we miss?
    l1_error = y - l1

    # multiply how much we missed by the
    # slope of the sigmoid at the values in l1
    
    l1_delta = l1_error * nonlin(l1,True)    

    # update weights
    syn0 += np.dot(l0.T,l1_delta)

In [13]:
print ("Output After Training:")
print (l1)


Output After Training:
[[0.00966449]
 [0.00786506]
 [0.99358898]
 [0.99211957]]
